export const SEARCH = {
  UPDATE_OWNER: 'UPDATE_OWNER',
  UPDATE_REPO: 'UPDATE_REPO',
  FIND_ISSUES: 'FIND_ISSUES',
  FIND_ISSUES_SUCCESS: 'FIND_ISSUES_SUCCESS',
  FIND_ISSUES_ERROR: 'FIND_ISSUES_ERROR',
  FIND_REPOS: 'FIND_REPOS',
  FIND_REPOS_SUCCESS: 'FIND_REPOS_SUCCESS',
  FIND_REPOS_ERROR: 'FIND_REPOS_ERROR'
}

export const PAGINATION = {
  SHOW_PER_PAGE: 'SHOW_PER_PAGE',
  CHANGE_PAGE: 'CHANGE_PAGE'
}
